name: NASA project CI/CD workflow
on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node version 16
        uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client