name: NASA project CI/CD workflow
on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
jobs:
  build: 
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
        mongodb-version: [ '4.4' ]
    steps:
      - uses: actions/checkout@v2
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm install --prefix client
      - run: npm run build --prefix client
      - run: npm install --prefix server
      - name: Setup MongoDB mock database
        uses: supercharge/mongodb-github-action@1.8.0
        with: 
          mongo-version: ${{ matrix.mongodb-version }}
      - run: npm test --prefix server